name: "debug"

on:
  push:
    branches: [ "perf*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows-release-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Release Build
      run: cargo build --release
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: lan-mouse-windows
        path: target/release/lan-mouse.exe
